apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/axvg/store-microservices/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/storedb?sslmode=disable
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: ORDER_SERVICE_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: JAVA_OPTS
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 15
